apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
    containers:
    - image: alpine
      name: alpine
      command: ["/bin/sleep"]
      args: ["999"]
      securityContext:
        privileged: true
