apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: policies.acmecorp.com
spec:
  group: acmecorp.com
  version: v1
  scope: Cluster
  names:
    plural: policies
    singular: policy
    kind: Policy
