apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: policies.stable.alice.io
spec:
  group: stable.alice.io
  version: v1
  scope: Cluster
  names:
    plural: policies
    singular: policy
    kind: Policy
